### ISSUE TITLE
Crash in example app

### ISSUE THREAD

**Issue by ligi** [TrustWallet/Web3View#4]
when typing in  thetokenfactory.com in the address bar:

```
D/REQUEST_ERROR: javax.net.ssl.SSLPeerUnverifiedException: Hostname thetokenfactory.com not verified:
                     certificate: sha256/x8itYf6E+sDl+En+Bthiu/qo1ux+8o1+pSSR5CqodP8=
                     DN: CN=*.surge.sh,OU=PositiveSSL Wildcard,OU=Domain Control Validated
                     subjectAltNames: [*.surge.sh, surge.sh]
                     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:316)
                     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:270)
                     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:162)
                     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
                     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
                     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
                     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                     at okhttp3.RealCall.execute(RealCall.java:77)
                     at trust.web3.JsInjectorClient.loadUrl(JsInjectorClient.java:79)
                     at trust.web3.Web3ViewClient.shouldInterceptRequest(Web3ViewClient.java:106)
                     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:307)
                     at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:523)
                     at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
W/System.err: java.lang.NullPointerException: Attempt to read from field 'boolean trust.web3.JsInjectorResponse.isRedirect' on a null object reference
                  at trust.web3.Web3ViewClient.shouldInterceptRequest(Web3ViewClient.java:110)
                  at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:307)
                  at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:523)
                  at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
A/chromium: [FATAL:jni_android.cc(236)] Please include Java exception stack in crash report


            --------- beginning of crash
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
                   Chrome build fingerprint:
                   1.0
                   1
                   ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 7687 (Chrome_FileThre)
Application terminated.

```

Btw.: which dApps are working with this web3view? I tried some - but had no real luck - tried akasha (white screen) - kyber (tells me I need to have metamask enabled) 
![screenshot_1528719384](https://user-images.githubusercontent.com/111600/41231554-ad177018-6d83-11e8-9ac2-41d04bab704a.png)
![screenshot_1528719844](https://user-images.githubusercontent.com/111600/41231534-9fbffb4c-6d83-11e8-88a7-f95ebf5a7d5c.png)

**Comment by ligi** [comment]
I can confirm the crash is gone now - but still having problems running any dApp in this webview
